### ISSUE TITLE
Task is triggered by backlog without parameters (sometimes)

### ISSUE THREAD

**Issue by oakulyk** [ametiste-oss/ametiste-routine-framework#25]
Sometimes task cannot be triggered by backlog. It's not a stable issue. I haven't found steps to reproduce it.

```
2016-08-03 18:45:53.153 DEBUG 1601 --- [pool-3-thread-1] o.a.r.a.s.issue.DefaultTaskIssueService  : New task created using scheme: generate-video-thumbs-task, task id: 7ba7d6ba-fdf4-4114-a9be-f159a50dc0c0, creator id: mod-backlog-renew-operation
2016-08-03 18:45:53.278 ERROR 1601 --- [pool-3-thread-4] o.a.r.i.e.l.LocalLineExecutionGateway    : Error during task operation execution : generate

java.lang.IllegalStateException: There is no resolved parameters.
    at org.ametiste.routine.dsl.application.DynamicOperationFactory.lambda$resolveMethodParameters$19(DynamicOperationFactory.java:72) ~[ametiste-routine-core-spring-1.1.0-b8.jar:na]
    at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_92]
    at org.ametiste.routine.dsl.application.DynamicOperationFactory.resolveMethodParameters(DynamicOperationFactory.java:72) ~[ametiste-routine-core-spring-1.1.0-b8.jar:na]
    at org.ametiste.routine.dsl.application.DynamicOperationFactory.lambda$createDynamicOperation$16(DynamicOperationFactory.java:53) ~[ametiste-routine-core-spring-1.1.0-b8.jar:na]
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_92]
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_92]
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_92]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_92]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_92]
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_92]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_92]
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_92]
    at org.ametiste.routine.dsl.application.DynamicOperationFactory.createDynamicOperation(DynamicOperationFactory.java:54) ~[ametiste-routine-core-spring-1.1.0-b8.jar:na]
    at org.ametiste.routine.dsl.application.DynamicOperationExecutor.execOperation(DynamicOperationExecutor.java:17) ~[ametiste-routine-core-spring-1.1.0-b8.jar:na]
    at org.ametiste.routine.infrastructure.execution.local.LocalLineExecutionGateway.executeOperation(LocalLineExecutionGateway.java:72) ~[ametiste-routine-core-1.1.0-b8.jar:na]
    at org.ametiste.routine.infrastructure.execution.local.LocalLineExecutionGateway$$FastClassBySpringCGLIB$$bb5f62bf.invoke(<generated>) [ametiste-routine-core-1.1.0-b8.jar:na]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) [spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) [spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.ametiste.metrics.aop.TimeableAspect.processTiming(TimeableAspect.java:72) [metrics-aop-0.2.0-RELEASE.jar:na]
    at sun.reflect.GeneratedMethodAccessor125.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:620) [spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:609) [spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68) [spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) [spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) [spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.ametiste.routine.infrastructure.execution.local.LocalLineExecutionGateway$$EnhancerBySpringCGLIB$$cb867290.executeOperation(<generated>) [ametiste-routine-core-1.1.0-b8.jar:na]
    at org.ametiste.routine.domain.task.ExecutionOrder.lambda$executionLines$15(ExecutionOrder.java:31) ~[ametiste-routine-core-1.1.0-b8.jar:na]
    at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_92]
    at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080) ~[na:1.8.0_92]
    at org.ametiste.routine.domain.task.ExecutionOrder.executionLines(ExecutionOrder.java:30) ~[ametiste-routine-core-1.1.0-b8.jar:na]
    at org.ametiste.routine.infrastructure.execution.local.LocalTaskExecutionGateway.lambda$startTaskExecution$28(LocalTaskExecutionGateway.java:63) ~[ametiste-routine-core-1.1.0-b8.jar:na]
    at org.ametiste.routine.infrastructure.execution.local.BoundedExecutor.lambda$submitTask$20(BoundedExecutor.java:24) ~[ametiste-routine-core-1.1.0-b8.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_92]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_92]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
```

**Comment by detsam** [comment]
Well, there are a bunch of possible reasons, I need to see the task definition to get details, but the first and the obviousness - nullable values for defined operation parameters.
